### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by x0ptr** [larsonnn/strapi-plugin-socket.io#4]
### After installing strapi-plugin-socket-io 2.1.0

MacBook Apple M1
MacOS 11.5.2
node -v v14.17.0

```
> node --trace-warnings --inspect=127.0.0.1:9229 ./node_modules/strapi/bin/strapi.js develop

Debugger listening on ws://127.0.0.1:9229/5b80793e-a5ed-44dc-99b3-50ad53512e0d
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:9230/696b340b-9e95-4c1c-bec4-eff799ec9467
For help, see: https://nodejs.org/en/docs/inspector
(node:50120) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:451:17)
    at WriteStream.addListener (events.js:467:10)
    at WriteStream.Readable.on (internal/streams/readable.js:867:35)
    at DestroyableTransform.Readable.pipe (/Users/lars/Documents/repos/strapio/tests/strapi2/node_modules/readable-stream/lib/_stream_readable.js:564:8)
    at DestroyableTransform.stream.pipe (/Users/lars/Documents/repos/strapio/tests/strapi2/node_modules/pino/pretty.js:154:17)
    at Object.<anonymous> (/Users/lars/Documents/repos/strapio/tests/strapi2/node_modules/strapi-plugin-users-permissions/node_modules/strapi-utils/lib/logger.js:56:8)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
(node:50120) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:451:17)
    at WriteStream.addListener (events.js:467:10)
    at WriteStream.Readable.on (internal/streams/readable.js:867:35)
    at DestroyableTransform.Readable.pipe (/Users/lars/Documents/repos/strapio/tests/strapi2/node_modules/readable-stream/lib/_stream_readable.js:585:8)
    at DestroyableTransform.stream.pipe (/Users/lars/Documents/repos/strapio/tests/strapi2/node_modules/pino/pretty.js:154:17)
    at Object.<anonymous> (/Users/lars/Documents/repos/strapio/tests/strapi2/node_modules/strapi-plugin-users-permissions/node_modules/strapi-utils/lib/logger.js:56:8)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
(node:50120) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:451:17)
    at WriteStream.prependListener (events.js:474:14)
    at prependListener (/Users/lars/Documents/repos/strapio/tests/strapi2/node_modules/readable-stream/lib/_stream_readable.js:92:69)
    at DestroyableTransform.Readable.pipe (/Users/lars/Documents/repos/strapio/tests/strapi2/node_modules/readable-stream/lib/_stream_readable.js:644:3)
    at DestroyableTransform.stream.pipe (/Users/lars/Documents/repos/strapio/tests/strapi2/node_modules/pino/pretty.js:154:17)
    at Object.<anonymous> (/Users/lars/Documents/repos/strapio/tests/strapi2/node_modules/strapi-plugin-users-permissions/node_modules/strapi-utils/lib/logger.js:56:8)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
(node:50120) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:451:17)
    at WriteStream.addListener (events.js:467:10)
    at WriteStream.Readable.on (internal/streams/readable.js:867:35)
    at WriteStream.once (events.js:498:8)
    at DestroyableTransform.Readable.pipe (/Users/lars/Documents/repos/strapio/tests/strapi2/node_modules/readable-stream/lib/_stream_readable.js:651:8)
    at DestroyableTransform.stream.pipe (/Users/lars/Documents/repos/strapio/tests/strapi2/node_modules/pino/pretty.js:154:17)
    at Object.<anonymous> (/Users/lars/Documents/repos/strapio/tests/strapi2/node_modules/strapi-plugin-users-permissions/node_modules/strapi-utils/lib/logger.js:56:8)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
(node:50120) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:451:17)
    at WriteStream.addListener (events.js:467:10)
    at WriteStream.Readable.on (internal/streams/readable.js:867:35)
    at WriteStream.once (events.js:498:8)
    at DestroyableTransform.Readable.pipe (/Users/lars/Documents/repos/strapio/tests/strapi2/node_modules/readable-stream/lib/_stream_readable.js:657:8)
    at DestroyableTransform.stream.pipe (/Users/lars/Documents/repos/strapio/tests/strapi2/node_modules/pino/pretty.js:154:17)
    at Object.<anonymous> (/Users/lars/Documents/repos/strapio/tests/strapi2/node_modules/strapi-plugin-users-permissions/node_modules/strapi-utils/lib/logger.js:56:8)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    ```

**Comment by x0ptr** [comment]
commit f0cd2e096a2cf0ac22e6fbd6d0fffaa960aea45d fixed that.
